apiVersion: v1
kind: Namespace
metadata:
  name: app-python
---
apiVersion: v1
kind: Service
metadata:
  namespace: app-python
  name: app
  labels:
    app: app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: app-python
  name: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "cesarbgoncalves/app:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
